/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/iwpWFCF3Idw
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Rethink_Sans } from 'next/font/google'
import { DM_Sans } from 'next/font/google'

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";

import { Footer, Header } from "@/components/home-page";
import { ProductList } from "@/components/product-list";
import React from "react";

interface ProductCategoryProps {}

interface ProductCategoryState {}

class ProductCategory extends React.Component<
  ProductCategoryProps,
  ProductCategoryState
> {
  constructor(props: ProductCategoryProps) {
    super(props);
    // this.state = { :  };
  }
  render() {
    return (
      <>
        <ProductList />
      </>
    );
  }
}

export default ProductCategory;
