/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/RLmzRQHO2I4
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

"use client";
require("dotenv").config();
import Link from "next/link";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { CardContent, Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import {
  Menubar,
  MenubarContent,
  MenubarItem,
  MenubarMenu,
  MenubarSeparator,
  MenubarTrigger,
} from "@/components/ui/menubar";
import { Textarea } from "@/components/ui/textarea";
import React, { useEffect, useState } from "react";
import { GoogleMap, LoadScript, Marker } from "@react-google-maps/api";
import { urlForImage } from "../../sanity/lib/image";
import { Category, Product } from "@/lib/typings";
import { useForm, SubmitHandler } from "react-hook-form";
import ProductCategories from "./product-categories";
import {
  PackageIcon,
  LightbulbIcon,
  TruckIcon,
  GlobeIcon,
  TargetIcon,
  ThumbsUpIcon,
  PhoneIcon,
  MailIcon,
  FacebookIcon,
  TwitterIcon,
  InstagramIcon,
  LocateIcon,
  LogInIcon,
  MenuIcon,
} from "@/components/ui/icons";
import { Hero } from "./hero";

type Inputs = {
  name: string;
  email: string;
  company: string;
  phone: string;
  message: string;
};

const containerStyle = {
  width: "100%",
  height: "400px",
};

const defaultCenter = {
  lat: 40.748817,
  lng: -73.985428,
};

const getCoordinates = async (address: string | number | boolean) => {
  const response = await fetch(
    `https://maps.googleapis.com/maps/api/geocode/json?address=${encodeURIComponent(address)}&key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}`
  );
  const data = await response.json();
  if (data.results.length > 0) {
    const { lat, lng } = data.results[0].geometry.location;
    return { lat, lng };
  }
  return null;
};

const Map = ({ apiKey, address }: any) => {
  const [center, setCenter] = useState(defaultCenter);

  useEffect(() => {
    if (address) {
      getCoordinates(address).then((coords) => {
        if (coords) {
          setCenter(coords);
        }
      });
    }
  }, [address]);

  return (
    <LoadScript googleMapsApiKey={apiKey}>
      <GoogleMap mapContainerStyle={containerStyle} center={center} zoom={14}>
        <Marker position={center} />
      </GoogleMap>
    </LoadScript>
  );
};

export function HomePage() {
  const [products, setProducts] = useState<Product[]>([]);
  const [categories, setCategories] = useState<Category[]>([]);
  const [submitting, setSubmitting] = useState(false);
  const [successMessage, setSuccessMessage] = useState("");
  const [failureMessage, setFailureMessage] = useState("");
  const { register, handleSubmit, reset } = useForm<Inputs>();

  const onSubmit: SubmitHandler<Inputs> = async (formData) => {
    setSubmitting(true);
    const to = "daniel.ameh@godavistore.com";
    const subject = "Message from Godavi Store";
    const text = formData.message;
    const html = `<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Introduction Email</title>
    </head>
    <body>
        
        <p>Hi Godavi Store,</p>
        
        <p>You just recieved a message from <strong>${formData.name}</strong>. They've sent you a message from your website:</p>
        
        <h2>Message:</h2>
        <p><strong>From:</strong> ${formData.name} &lt;${formData.email}&gt;</p>
        <p><strong>Phone Number:</strong> ${formData.phone} </p>
        <p><strong>Company Name:</strong> ${formData.company} </p>
        <p><strong>Message:</strong> ${formData.message}</p>
        
        <p>Best regards,<br>
        Your Name</p>
        Godavi Notifications.
    </body>
    </html>`;

    const emailStatus = await fetch(
      `${process.env.NEXT_PUBLIC_BASE_URL}/api/sendemail`,
      { method: "POST", body: JSON.stringify({ to, subject, text, html }) }
    );
    const data = await emailStatus.json();
    console.log(data);
    if (data.message.includes("success")) {
      setSuccessMessage(data.message);
      reset(); // Clear form fields
    } else {
      setFailureMessage(data.message);
    }
    setSubmitting(false);
  };

  useEffect(() => {
    async function fetchData() {
      const get_products = await fetch(
        `${process.env.NEXT_PUBLIC_BASE_URL}/api/products`,
        { next: { revalidate: 30 } }
      );
      const get_categories = await fetch(
        `${process.env.NEXT_PUBLIC_BASE_URL}/api/categories`,
        { next: { revalidate: 30 } }
      );
      const get_products_data = await get_products.json();
      const get_categories_data = await get_categories.json();

      setProducts(get_products_data.products);
      setCategories(get_categories_data.categories);
    }
    fetchData();
  }, []);

  return (
    <div className="flex flex-col min-h-[100dvh] flex-grow">
      <div className="flex-1">
        <Hero />
        <ProductCategories categories={categories} />
        <section className="bg-gray-100 py-20 px-6 md:px-12">
          <div className="max-w-5xl mx-auto space-y-8">
            <div className="text-center space-y-4">
              <h2 className="text-3xl font-bold">Featured Products</h2>
              <p className="text-gray-600">
                Explore our curated selection of the best products for your
                needs.
              </p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
              {products
                .filter((product) => product.featured === true)
                .map((product) => (
                  <Card key={product._id}>
                    <Image
                      alt={product.title}
                      className="rounded-t-lg w-full"
                      height="300"
                      src={urlForImage(product.images[0]) ?? ""} // Assuming each product has an image property
                      width="300"
                    />
                    <CardContent className="p-4 space-y-2">
                      <h3 className="text-xl font-bold">{product.title}</h3>
                      <p className="text-gray-600">
                        {product.description?.slice(0, 120)} . . .
                      </p>
                      {/* <div className="flex justify-between items-center">
                      {/* <span className="font-bold text-blue-500">
                        ${product.price}
                      </span>{" "}
                      <Link
                        className="inline-flex h-8 items-center justify-center rounded-md bg-blue-500 px-4 text-sm font-medium text-white shadow transition-colors hover:bg-blue-600 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-blue-950 disabled:pointer-events-none disabled:opacity-50"
                        href="#"
                      >
                        Add to Cart
                      </Link>
                    </div> */}
                    </CardContent>
                  </Card>
                ))}
            </div>
          </div>
        </section>
        <section id="services" className="bg-white py-20 px-6 md:px-12">
          <div className="max-w-5xl mx-auto space-y-8">
            <div className="text-center space-y-4">
              <h2 className="text-3xl font-bold">Our Services</h2>
              <p className="text-gray-600">
                Godavi offers a wide range of services to meet your needs.
              </p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div className="space-y-4">
                <PackageIcon className="h-12 w-12 text-blue-500" />
                <h3 className="text-xl font-bold">
                  Reselling Established Brands
                </h3>
                <p className="text-gray-600">
                  We specialize in reselling established brand products to our
                  customers.
                </p>
              </div>
              <div className="space-y-4">
                <LightbulbIcon className="h-12 w-12 text-blue-500" />
                <h3 className="text-xl font-bold">
                  Innovative Product Development
                </h3>
                <p className="text-gray-600">
                  We are developing innovative products for the global
                  marketplace.
                </p>
              </div>
              <div className="space-y-4">
                <TruckIcon className="h-12 w-12 text-blue-500" />
                <h3 className="text-xl font-bold">Comprehensive Logistics</h3>
                <p className="text-gray-600">
                  We provide comprehensive logistics solutions to our customers.
                </p>
              </div>
              <div className="space-y-4">
                <GlobeIcon className="h-12 w-12 text-blue-500" />
                <h3 className="text-xl font-bold">Multi-Channel Sales</h3>
                <p className="text-gray-600">
                  We sell on multiple channels including Canada Walmart,
                  international wholesale distribution to warehouses, and Amazon
                  US.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-white py-20 px-6 md:px-12">
          <div className="max-w-5xl mx-auto space-y-8">
            <div className="text-center space-y-4">
              <h2 className="text-3xl font-bold">Our Mission</h2>
              <p className="text-gray-600">
                Godavi is committed to achieving our mission.
              </p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div className="space-y-4">
                <TargetIcon className="h-12 w-12 text-blue-500" />
                <h3 className="text-xl font-bold">Enduring Business</h3>
                <p className="text-gray-600">
                  To establish Godavi as a successful and enduring business for
                  generations to come.
                </p>
              </div>
              <div className="space-y-4">
                <ThumbsUpIcon className="h-12 w-12 text-blue-500" />
                <h3 className="text-xl font-bold">Customer Satisfaction</h3>
                <p className="text-gray-600">
                  To ensure customer satisfaction and provide exceptional value.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section id="contact" className="bg-white py-20 px-6 md:px-12">
          <div className="max-w-5xl mx-auto grid md:grid-cols-2 gap-8">
            <div className="space-y-4">
              <h2 className="text-3xl font-bold">Contact Us</h2>
              <p className="text-gray-600">
                Have a question or feedback? We&apos;d love to hear from you.
              </p>
              <div className="flex flex-col md:flex-row gap-4">
                <div className="flex items-center gap-2">
                  <PhoneIcon className="h-5 w-5 text-gray-500" />
                  <span className="text-gray-600">+19374890684</span>
                </div>
                <div className="flex items-center gap-2">
                  <MailIcon className="h-5 w-5 text-gray-500" />
                  <span className="text-gray-600">info@godavistore.com</span>
                </div>
                <div className="flex items-center gap-2">
                  <Link className="hover:underline" href="#">
                    <FacebookIcon className="h-5 w-5 text-gray-500" />
                  </Link>
                  <Link className="hover:underline" href="#">
                    <TwitterIcon className="h-5 w-5 text-gray-500" />
                  </Link>
                  <Link className="hover:underline" href="#">
                    <InstagramIcon className="h-5 w-5 text-gray-500" />
                  </Link>
                </div>
              </div>
              <div className="flex flex-col md:flex-row gap-4">
                <div className="flex items-center gap-2">
                  <LocateIcon className="h-5 w-5 text-gray-500" />
                  <span className="text-gray-600">
                    7801 Congress St, New Port Richey, Florida, 34653
                  </span>
                </div>
              </div>
              <div className="pt-4">
                <Map
                  apiKey={process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
                  address="7801 Congress St, New Port Richey, Florida, 34653"
                />
              </div>
            </div>
            <form
              onSubmit={handleSubmit(onSubmit)}
              className="bg-gray-100 p-6 rounded-lg shadow-md"
            >
              <h3 className="text-2xl font-bold mb-4">Get in Touch</h3>
              <div className="grid grid-cols-1 gap-4">
                <div>
                  <label
                    className="block text-gray-700 font-medium mb-2"
                    htmlFor="name"
                  >
                    Full Name
                  </label>
                  <Input
                    {...register("name")}
                    required
                    id="name"
                    placeholder="Enter your name"
                    type="text"
                  />
                </div>
                <div>
                  <label
                    className="block text-gray-700 font-medium mb-2"
                    htmlFor="company"
                  >
                    Company
                  </label>
                  <Input
                    {...register("company")}
                    id="company"
                    placeholder="Enter your company"
                    type="text"
                  />
                </div>
                <div>
                  <label
                    className="block text-gray-700 font-medium mb-2"
                    htmlFor="email"
                  >
                    Email
                  </label>
                  <Input
                    {...register("email")}
                    required
                    id="email"
                    placeholder="Enter your email"
                    type="email"
                  />
                </div>
                <div>
                  <label
                    className="block text-gray-700 font-medium mb-2"
                    htmlFor="phone"
                  >
                    Phone
                  </label>
                  <Input
                    {...register("phone")}
                    id="phone"
                    placeholder="Enter your phone number"
                    type="text"
                  />
                </div>
                <div>
                  <label
                    className="block text-gray-700 font-medium mb-2"
                    htmlFor="message"
                  >
                    Message
                  </label>
                  <Textarea
                    {...register("message")}
                    id="message"
                    required
                    placeholder="Enter your message"
                    rows={5}
                  />
                </div>
                <Button
                  type="submit"
                  variant="default"
                  size="default"
                  disabled={submitting}
                >
                  {submitting ? "Submitting..." : "Submit"}
                </Button>
              </div>
              {successMessage && (
                <p className="text-green-900 text-md border-4 text-center py-3 md:py-5 px-10 rounded-lg border-lime-200 bg-green-100 font-semibold animate-pulse">
                  {successMessage}
                </p>
              )}
              {failureMessage && (
                <p className="text-red-900 text-md border-4 text-center py-3 md:py-5 px-10 rounded-lg border-orange-200 bg-red-100 p-4 font-semibold animate-pulse">
                  {failureMessage}
                </p>
              )}
            </form>
          </div>
        </section>
      </div>
    </div>
  );
}

export function Footer() {
  const year = new Date().getFullYear();
  return (
    <footer className="bg-black text-white py-8 px-6 md:px-12">
      <div className="max-w-5xl mx-auto flex flex-col md:flex-row justify-between items-center gap-4">
        <div className="flex items-center gap-2">
          <LogInIcon className="h-8 w-8" />
          <span className="text-lg font-semibold">Godavi</span>
        </div>
        <nav className="flex items-center gap-6">
          <Link href="/" className="hover:underline" prefetch={false}>
            Home
          </Link>
          <Link
            href="/categories/all"
            className="hover:underline"
            prefetch={false}
          >
            Store
          </Link>
          <Link href="/about" className="hover:underline" prefetch={false}>
            About
          </Link>
          <Link href="/#contact" className="hover:underline" prefetch={false}>
            Contact
          </Link>
        </nav>
        <p className="text-sm text-gray-400">
          &copy; {year} Godavi. All rights reserved.
        </p>
      </div>
    </footer>
  );
}

export function Header() {
  return (
    <header className="bg-black text-white py-4 px-6 md:px-12 flex items-center justify-between">
      <Link className="flex items-center gap-2" href="/">
        <LogInIcon className="h-8 w-8" />
        <span className="text-lg font-semibold">GODAVI</span>
      </Link>
      <nav className="hidden md:flex items-center gap-6">
        <Link className="hover:underline" href="/">
          Home
        </Link>
        <Link className="hover:underline" href="/categories/all">
          Store
        </Link>
        <Link className="hover:underline" href="/about">
          About
        </Link>
        <Link className="hover:underline" href="/#services">
          Our Services
        </Link>
        <Link className="hover:underline" href="/#contact">
          Contact
        </Link>
      </nav>
      <div className="md:hidden">
        <Menubar>
          <MenubarMenu>
            <MenubarTrigger>
              <MenuIcon className="h-6 w-6 text-gray-900" />
            </MenubarTrigger>
            <MenubarContent>
              <MenubarItem>
                <Link className="hover:underline" href="/">
                  Home
                </Link>
              </MenubarItem>
              <MenubarItem>
                <Link className="hover:underline" href="/categories/all">
                  Store
                </Link>
              </MenubarItem>
              <MenubarItem>
                {" "}
                <Link className="hover:underline" href="/about">
                  About
                </Link>
              </MenubarItem>
              <MenubarSeparator />
              <MenubarItem>
                <Link className="hover:underline" href="#">
                  Our Services
                </Link>
              </MenubarItem>
              <MenubarItem>
                <Link className="hover:underline" href="#contact">
                  Contact
                </Link>
              </MenubarItem>
            </MenubarContent>
          </MenubarMenu>
        </Menubar>
      </div>
    </header>
  );
}
