/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/5F2VUVShwGp
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { JSX, SVGProps } from "react"

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function SalesChannels() {
  return (
    <section id="sales-channels" className="bg-gray-100 py-20 px-6 md:px-12">
      <div className="max-w-5xl mx-auto space-y-8">
        <div className="text-center space-y-4">
          <h2 className="text-3xl font-bold">Our Sales Channels</h2>
          <p className="text-gray-600">
          We strategize to sell our products across several key marketplaces to maximize exposure and reach a broad audience.
          </p>
        </div>
        <div className="grid grid-cols-1 gap-6 sm:grid-cols-3 md:grid-cols-3">
          <div className="group flex flex-col items-center justify-center space-y-4 rounded-lg bg-background p-6 transition-all hover:bg-accent hover:text-accent-foreground">
            <div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary text-primary-foreground transition-all group-hover:scale-110 group-hover:bg-accent group-hover:text-accent-foreground">
              <RecycleIcon className="h-10 w-10 text-green-500" />
            </div>
            <div className="space-y-1">
              <h3 className="text-lg font-bold">Retail Stores</h3>
              <p className="text-muted-foreground">
                Partnering with brick-and-mortar stores to offer your products directly to consumers.
              </p>
            </div>
          </div>
          <div className="group flex flex-col items-center justify-center space-y-4 rounded-lg bg-background p-6 transition-all hover:bg-accent hover:text-accent-foreground">
            <div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary text-primary-foreground transition-all group-hover:scale-110 group-hover:bg-accent group-hover:text-accent-foreground">
              <WarehouseIcon className="h-10 w-10 text-blue-500" />
            </div>
            <div className="space-y-1">
              <h3 className="text-lg font-bold">Wholesale Partnerships</h3>
              <p className="text-muted-foreground">
                Establishing relationships with wholesale distributors for wider distribution.
              </p>
            </div>
          </div>
          <div className="group flex flex-col items-center justify-center space-y-4 rounded-lg bg-background p-6 transition-all hover:bg-accent hover:text-accent-foreground">
            <div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary text-primary-foreground transition-all group-hover:scale-110 group-hover:bg-accent group-hover:text-accent-foreground">
              <LuggageIcon className="h-10 w-10 text-orange-500" />
            </div>
            <div className="space-y-1">
              <h3 className="text-lg font-bold">Distribution to Warehouses</h3>
              <p className="text-muted-foreground">
                Strategically placing products in key warehouses to optimize logistics and delivery times.
              </p>
            </div>
          </div>
          <div className="group flex flex-col items-center justify-center space-y-4 rounded-lg bg-background p-6 transition-all hover:bg-accent hover:text-accent-foreground">
            <div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary text-primary-foreground transition-all group-hover:scale-110 group-hover:bg-accent group-hover:text-accent-foreground">
              <ShoppingCartIcon className="h-10 w-10 text-purple-500" />
            </div>
            <div className="space-y-1">
              <h3 className="text-lg font-bold">Our own e-commerce site</h3>
              <p className="text-muted-foreground">Currently in development to promote and sell products directly.</p>
            </div>
          </div>
          <div className="group flex flex-col items-center justify-center space-y-4 rounded-lg bg-background p-6 transition-all hover:bg-accent hover:text-accent-foreground">
            <div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary text-primary-foreground transition-all group-hover:scale-110 group-hover:bg-accent group-hover:text-accent-foreground">
              <StoreIcon className="h-10 w-10 text-red-500" />
            </div>
            <div className="space-y-1">
              <h3 className="text-lg font-bold">Amazon US, Walmart</h3>
              <p className="text-muted-foreground">
                Leveraging Amazon&apos;s and Walmart&apos;s extensive reach and robust fulfillment services.
              </p>
            </div>
          </div>
          <div className="group flex flex-col items-center justify-center space-y-4 rounded-lg bg-background p-6 transition-all hover:bg-accent hover:text-accent-foreground">
            <div className="flex h-12 w-12 items-center justify-center rounded-full bg-primary text-primary-foreground transition-all group-hover:scale-110 group-hover:bg-accent group-hover:text-accent-foreground">
              <GlobeIcon className="h-10 w-10 text-blue-500" />
            </div>
            <div className="space-y-1">
              <h3 className="text-lg font-bold">International Markets</h3>
              <p className="text-muted-foreground">
                Expanding our reach to international markets and leveraging global distribution channels.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

function AppleIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 20.94c1.5 0 2.75 1.06 4 1.06 3 0 6-8 6-12.22A4.91 4.91 0 0 0 17 5c-2.22 0-4 1.44-5 2-1-.56-2.78-2-5-2a4.9 4.9 0 0 0-5 4.78C2 14 5 22 8 22c1.25 0 2.5-1.06 4-1.06Z" />
      <path d="M10 2c1 .5 2 2 2 5" />
    </svg>
  )
}


function GlobeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20" />
      <path d="M2 12h20" />
    </svg>
  )
}


function LuggageIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 20h0a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h0" />
      <path d="M8 18V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v14" />
      <path d="M10 20h4" />
      <circle cx="16" cy="20" r="2" />
      <circle cx="8" cy="20" r="2" />
    </svg>
  )
}


function RecycleIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7 19H4.815a1.83 1.83 0 0 1-1.57-.881 1.785 1.785 0 0 1-.004-1.784L7.196 9.5" />
      <path d="M11 19h8.203a1.83 1.83 0 0 0 1.556-.89 1.784 1.784 0 0 0 0-1.775l-1.226-2.12" />
      <path d="m14 16-3 3 3 3" />
      <path d="M8.293 13.596 7.196 9.5 3.1 10.598" />
      <path d="m9.344 5.811 1.093-1.892A1.83 1.83 0 0 1 11.985 3a1.784 1.784 0 0 1 1.546.888l3.943 6.843" />
      <path d="m13.378 9.633 4.096 1.098 1.097-4.096" />
    </svg>
  )
}


function ShoppingCartIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  )
}


function StoreIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m2 7 4.41-4.41A2 2 0 0 1 7.83 2h8.34a2 2 0 0 1 1.42.59L22 7" />
      <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8" />
      <path d="M15 22v-4a2 2 0 0 0-2-2h-2a2 2 0 0 0-2 2v4" />
      <path d="M2 7h20" />
      <path d="M22 7v3a2 2 0 0 1-2 2v0a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 16 12a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 12 12a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 8 12a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 4 12v0a2 2 0 0 1-2-2V7" />
    </svg>
  )
}


function WarehouseIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 8.35V20a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V8.35A2 2 0 0 1 3.26 6.5l8-3.2a2 2 0 0 1 1.48 0l8 3.2A2 2 0 0 1 22 8.35Z" />
      <path d="M6 18h12" />
      <path d="M6 14h12" />
      <rect width="12" height="12" x="6" y="10" />
    </svg>
  )
}


function XIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
